# APIs

Instead of downloading World Bank data via a csv file, you're going to download the data using the World Bank APIs. The purpose of this exercise is to gain experience with another way of extracting data.

API is an acronym that stands for application programming interface. API’s provide a standardized way for two applications to talk to each other. In this case, the applications communicating with each other are the server application where World Bank stores data and your Jupyter notebook.

If you wanted to pull data directly from the World Bank’s server, you’d have to know what database system the World Bank was using. You’d also need permission to log in directly to the server, which would be a security risk for the World Bank. And if the World Bank ever migrated its data to a new system, you would have to rewrite all of your code again. The API allows you to execute code on the World Bank server without getting direct access.

# Before there were APIs

Before there were APIs, there was web scraping. People would download html directly from a website and then parse the results programatically. This practice is in a legal grey area. One reason that APIs became popular was so that companies could provide data to users and discourage web scraping.

Here are a few articles about the legality of web scraping.

* [QVC Can't Stop Web Scraping](https://www.forbes.com/sites/ericgoldman/2015/03/24/qvc-cant-stop-web-scraping/#120db59b3ca3)
* [Quora - Legality of Web Scraping](https://www.quora.com/What-is-the-legality-of-web-scraping)

All sorts of companies have public facing APIs including Facebook, Twitter, Google and Pinterest. You can pull data from these companies to create your own applications.

In this notebook, you’ll get practice using Python to pull data from the World Bank indicators API.

Here are links to information about the World Bank indicators and projects APIs if you want to learn more:
* [World Bank Indicators API](world bank projects api)
* [World Bank Projects API](http://search.worldbank.org/api/v2/projects)

# Using APIs

In general, you access APIs via the web using a web address. Within the web address, you specify the data that you want. To know how to format the web address, you need to read an API's documentation. Some APIs also require that you send login credentials as part of your request. The World Bank APIs are public and do not require login credentials.

The Python requests library makes working with APIs relatively simple.

# Example Indicators API

Run the code example below to request data from the World Bank Indicators API. According to the documntation, you format your request url like so:

`http://api.worldbank.org/v2/countries/` + list of country abbreviations separated by ; + `/indicators/` + indicator name + `?` + options

where options can include
* per_page - number of records to return per page
* page - which page to return - eg if there are 5000 records and 100 records per page
* date - filter by dates
* format - json or xml
 
 and a few other options that you can read about [here](https://datahelpdesk.worldbank.org/knowledgebase/articles/898581-api-basic-call-structure).

In [1]:
import requests
import pandas as pd

url = 'http://api.worldbank.org/v2/countries/br;cn;us;de/indicators/SP.POP.TOTL/?format=json&per_page=1000'
r = requests.get(url)
r.json()

[{'page': 1,
  'pages': 1,
  'per_page': 1000,
  'total': 244,
  'sourceid': '2',
  'sourcename': 'World Development Indicators',
  'lastupdated': '2021-04-26'},
 [{'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2020',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2019',
   'value': 211049527,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2018',
   'value': 209469333,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2017',
   'value': 207833831,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2016',
   'value': 206163058,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2015',
   'value': 204471769,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2014',
   'value': 202763735,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2013',
   'value': 201035903,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2012',
   'value': 199287296,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2011',
   'value': 197514534,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2010',
   'value': 195713635,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2009',
   'value': 193886508,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2008',
   'value': 192030362,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2007',
   'value': 190130443,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2006',
   'value': 188167356,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2005',
   'value': 186127103,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2004',
   'value': 184006481,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2003',
   'value': 181809246,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2002',
   'value': 179537520,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2001',
   'value': 177196054,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2000',
   'value': 174790340,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1999',
   'value': 172318675,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1998',
   'value': 169785250,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1997',
   'value': 167209040,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1996',
   'value': 164614688,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1995',
   'value': 162019896,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1994',
   'value': 159432716,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1993',
   'value': 156849078,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1992',
   'value': 154259380,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1991',
   'value': 151648011,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1990',
   'value': 149003223,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1989',
   'value': 146328304,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1988',
   'value': 143627503,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1987',
   'value': 140891602,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1986',
   'value': 138108912,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1985',
   'value': 135274080,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1984',
   'value': 132383568,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1983',
   'value': 129448819,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1982',
   'value': 126498314,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1981',
   'value': 123570327,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1980',
   'value': 120694009,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1979',
   'value': 117878411,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1978',
   'value': 115121153,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1977',
   'value': 112425392,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1976',
   'value': 109790938,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1975',
   'value': 107216205,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1974',
   'value': 104706198,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1973',
   'value': 102259497,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1972',
   'value': 99859383,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1971',
   'value': 97482920,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1970',
   'value': 95113265,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1969',
   'value': 92746614,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1968',
   'value': 90387079,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1967',
   'value': 88035814,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1966',
   'value': 85696505,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1965',
   'value': 83373530,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1964',
   'value': 81064571,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1963',
   'value': 78772657,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1962',
   'value': 76514328,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1961',
   'value': 74311343,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1960',
   'value': 72179226,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2020',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2019',
   'value': 1397715000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2018',
   'value': 1392730000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2017',
   'value': 1386395000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2016',
   'value': 1378665000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2015',
   'value': 1371220000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2014',
   'value': 1364270000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2013',
   'value': 1357380000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2012',
   'value': 1350695000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2011',
   'value': 1344130000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2010',
   'value': 1337705000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2009',
   'value': 1331260000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2008',
   'value': 1324655000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2007',
   'value': 1317885000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2006',
   'value': 1311020000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2005',
   'value': 1303720000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2004',
   'value': 1296075000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2003',
   'value': 1288400000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2002',
   'value': 1280400000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2001',
   'value': 1271850000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2000',
   'value': 1262645000,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},

This json data isn't quite ready for a pandas data frame. Notice that the json response is a list with two entries. The first entry is 
```
{'lastupdated': '2018-06-28',
  'page': 1,
  'pages': 1,
  'per_page': 1000,
  'total': 232}
```

That first entry is meta data about the results. For example, it says that there is one page returned with 232 results. 

The second entry is another list containing the data. This data would need some cleaning to be used in a pandas data frame. That would happen later in the transformation step of an ETL pipeline. Run the cell below to read the results into a dataframe and see what happens.

In [2]:
###
# Run this cell that converts the json into a dataframe
# Note that you do not need the pd.read_json() method because this is not a file or a string containing json 
##

pd.DataFrame(r.json()[1])

,country,countryiso3code,date,decimal,indicator,obs_status,unit,value
0,"{'id': 'BR', 'value': 'Brazil'}",BRA,2020,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,NaN
1,"{'id': 'BR', 'value': 'Brazil'}",BRA,2019,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,211049527.0
2,"{'id': 'BR', 'value': 'Brazil'}",BRA,2018,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,209469333.0
3,"{'id': 'BR', 'value': 'Brazil'}",BRA,2017,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,207833831.0
4,"{'id': 'BR', 'value': 'Brazil'}",BRA,2016,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,206163058.0
5,"{'id': 'BR', 'value': 'Brazil'}",BRA,2015,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,204471769.0
6,"{'id': 'BR', 'value': 'Brazil'}",BRA,2014,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,202763735.0
7,"{'id': 'BR', 'value': 'Brazil'}",BRA,2013,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,201035903.0
8,"{'id': 'BR', 'value': 'Brazil'}",BRA,2012,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,199287296.0
9,"{'id': 'BR', 'value': 'Brazil'}",BRA,2011,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,197514534.0
10,"{'id': 'BR', 'value': 'Brazil'}",BRA,2010,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,195713635.0
11,"{'id': 'BR', 'value': 'Brazil'}",BRA,2009,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,193886508.0
12,"{'id': 'BR', 'value': 'Brazil'}",BRA,2008,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,192030362.0
13,"{'id': 'BR', 'value': 'Brazil'}",BRA,2007,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,190130443.0
14,"{'id': 'BR', 'value': 'Brazil'}",BRA,2006,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,188167356.0
15,"{'id': 'BR', 'value': 'Brazil'}",BRA,2005,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,186127103.0
16,"{'id': 'BR', 'value': 'Brazil'}",BRA,2004,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,184006481.0
17,"{'id': 'BR', 'value': 'Brazil'}",BRA,2003,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,181809246.0
18,"{'id': 'BR', 'value': 'Brazil'}",BRA,2002,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,179537520.0
19,"{'id': 'BR', 'value': 'Brazil'}",BRA,2001,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,177196054.0
20,"{'id': 'BR', 'value': 'Brazil'}",BRA,2000,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,174790340.0
21,"{'id': 'BR', 'value': 'Brazil'}",BRA,1999,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,172318675.0
22,"{'id': 'BR', 'value': 'Brazil'}",BRA,1998,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,169785250.0
23,"{'id': 'BR', 'value': 'Brazil'}",BRA,1997,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,167209040.0
24,"{'id': 'BR', 'value': 'Brazil'}",BRA,1996,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,164614688.0
25,"{'id': 'BR', 'value': 'Brazil'}",BRA,1995,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,162019896.0
26,"{'id': 'BR', 'value': 'Brazil'}",BRA,1994,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,159432716.0
27,"{'id': 'BR', 'value': 'Brazil'}",BRA,1993,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,156849078.0
28,"{'id': 'BR', 'value': 'Brazil'}",BRA,1992,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,154259380.0
29,"{'id': 'BR', 'value': 'Brazil'}",BRA,1991,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,151648011.0
...,...,...,...,...,...,...,...,...
214,"{'id': 'US', 'value': 'United States'}",USA,1989,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,246819000.0
215,"{'id': 'US', 'value': 'United States'}",USA,1988,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,244499000.0
216,"{'id': 'US', 'value': 'United States'}",USA,1987,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,242289000.0
217,"{'id': 'US', 'value': 'United States'}",USA,1986,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,240133000.0
218,"{'id': 'US', 'value': 'United States'}",USA,1985,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,237924000.0
219,"{'id': 'US', 'value': 'United States'}",USA,1984,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,235825000.0
220,"{'id': 'US', 'value': 'United States'}",USA,1983,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,233792000.0
221,"{'id': 'US', 'value': 'United States'}",USA,1982,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,231664000.0
222,"{'id': 'US', 'value': 'United States'}",USA,1981,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,229466000.0
223,"{'id': 'US', 'value': 'United States'}",USA,1980,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,227225000.0
224,"{'id': 'US', 'value': 'United States'}",USA,1979,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,225055000.0
225,"{'id': 'US', 'value': 'United States'}",USA,1978,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,222585000.0
226,"{'id': 'US', 'value': 'United States'}",USA,1977,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,220239000.0
227,"{'id': 'US', 'value': 'United States'}",USA,1976,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,218035000.0
228,"{'id': 'US', 'value': 'United States'}",USA,1975,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,215973000.0
229,"{'id': 'US', 'value': 'United States'}",USA,1974,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,213854000.0
230,"{'id': 'US', 'value': 'United States'}",USA,1973,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,211909000.0
231,"{'id': 'US', 'value': 'United States'}",USA,1972,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,209896000.0
232,"{'id': 'US', 'value': 'United States'}",USA,1971,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,207661000.0
233,"{'id': 'US', 'value': 'United States'}",USA,1970,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,205052000.0
234,"{'id': 'US', 'value': 'United States'}",USA,1969,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,202677000.0
235,"{'id': 'US', 'value': 'United States'}",USA,1968,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,200706000.0
236,"{'id': 'US', 'value': 'United States'}",USA,1967,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,198712000.0
237,"{'id': 'US', 'value': 'United States'}",USA,1966,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,196560000.0
238,"{'id': 'US', 'value': 'United States'}",USA,1965,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,194303000.0
239,"{'id': 'US', 'value': 'United States'}",USA,1964,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,191889000.0
240,"{'id': 'US', 'value': 'United States'}",USA,1963,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,189242000.0
241,"{'id': 'US', 'value': 'United States'}",USA,1962,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,186538000.0
242,"{'id': 'US', 'value': 'United States'}",USA,1961,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,183691000.0
243,"{'id': 'US', 'value': 'United States'}",USA,1960,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,180671000.0

There are some issues with this dataframe. The country and indicator variables don't look particularly useful in their current form. Again, dealing with those issues would come in the transformation phase of a pipeline, which comes later in the lesson.

# Exercise Indicators API

Use the Indicators API to request rural population data for Switzerland in the years 1995 through 2001. Here are a few helpful resources:
* [documentation included how to filter by year](https://datahelpdesk.worldbank.org/knowledgebase/articles/898581-api-basic-call-structure)
* [2-character iso country codes](https://www.nationsonline.org/oneworld/country_code_list.htm)
* [search box for World Bank indicators](https://data.worldbank.org)

To find the indicator code, first search for the indicator here: https://data.worldbank.org
Click on the indicator name. The indicator code is in the url. For example, the indicator code for total population is SP.POP.TOTL, which you can see in the link [https://data.worldbank.org/indicator/SP.RUR.TOTL](https://data.worldbank.org/indicator/SP.RUR.TOTL).

In [5]:
# TODO: get the url ready
url = 'http://api.worldbank.org/v2/countries/ch/indicators/SP.POP.TOTL/?format=json&per_page=1000'

url = 'http://search.worldbank.org/api/v2/projects?format=json&qterm=rural+population&fl=countryname&lang_exact=English&source=IBRD&srt=score&order=desc&frmYear=2000&toYear=2001'

# TODO: send the request
r = requests.get(url)
r.json()

# TODO: output the json using the json method like in the previous example

{'rows': 10,
 'os': '0',
 'page': '1',
 'total': '88',
 'projects': {'P075549': {'id': 'P075549',
   'countryname': ['Georgia'],
   'project_name': 'Georgia Health Project Supplemental Credit',
   'project_abstract': {'cdata': "The Health Project will support the health sector reform efforts the government has initiated and will aim to improve the health of the Georgian population. The project's specific objectives are to: 1) reorient the health system towards cost-effective public health interventions like preventive and primary health care, assuring, in particular, better quality care for women and children, and focusing the Ministry of Health's (MOH) activities on regulation of public and private providers; 2) rehabilitate selected facilities and equipment that were down-sized and dedicated to cost-effective provision of maternal, perinatal and pediatric care; 3) develop human resources to support health reform, through continuing education for public health doctors, family practitioners, nurses, health administrators, and other personnel; and 4) support the development of an independent health fund with regional branches, in order to finance a package of basic clinical services in a cost-effective and equitable manner. The project consists of the following components: 1) health system reorientation, which includes: (a) modernization of public health services, health promotion and disease prevention; (b) healthy children and safe motherhood; and (c) realignment of MOH; 2) rehabilitation and maintenance of health facilities and equipment; 3) development of health human resources; 4) modernization of the health financing system; and 5) project administration."},
   'url': 'https://projects.worldbank.org/en/projects-operations/project-detail/P075549'},
  'P073911': {'id': 'P073911',
   'countryname': ['Democratic Republic of Timor-Leste'],
   'project_name': 'Second Agriculture Rehabilitation Project',
   'project_abstract': {'cdata': 'The Second Agriculture Rehabilitation Project, aims to improve food security of rural populations, and increase agricultural production in selected areas of East Timor. Through its components, the project will: 1) pilot an approach to strengthen the resilience of poor farming communities, by improving the management of natural resources, and the diverse sources of income. Through the provision of small grants, community proposals will be funded against in-kind labor, and materials. Training to farmers will include applied technical, and participatory methods, as well as monitoring and evaluation of projects; 2) increase agricultural production in irrigated areas, by financing the rehabilitation, and maintenance works on community-based irrigation schemes, farm-to-market access roads, including larger damaged irrigation schemes. Water Users Associations in the irrigated areas will be consolidated, and, an irrigation operational policy will be developed. All this entails training in irrigation management, as well as a monitoring and evaluation criteria; 3) provide essential services to farmers, to bridge transitional difficulties, and will gradually introduce private delivery mechanisms, through the development of information programs, and the establishment of liaison groups, to provide agricultural expertise, and technical assistance to farmers, including sustainable animal health services; and, 4) finance policy studies, technical assistance and incremental operating costs, to support project management and capacity building.'},
   'url': 'https://projects.worldbank.org/en/projects-operations/project-detail/P073911'},
  'P070294': {'id': 'P070294',
   'countryname': ['Democratic Republic of Timor-Leste'],
   'project_name': 'Health Sector Rehabilitation and Development Project',
   'project_abstract': {'cdata': 'The Health Sector Rehabilitation and Development Program Project for East Timor aims to immediately address basic health needs of the population of East Timor and develop policies and a suitable health system. There are two main project components. The first component restores access to basic health services and focuses on accelerated delivery of selected high priority programs (immunizations, TB, nutrition, health promotion) and service providers at the district level to provide a basic package of services. The transitional strategy also supports temporary repairs, some new building, and re-equipment. It re-establishes an administrative infrastructure and provides training for service delivery, management, and administration. It also prepares an action plan for excess hospital capacity. A major part of this component involves establishing pharmaceuticals/logistics systems. It will promote stakeholder participation through various consultation schemes. The second component addresses medium to long-term issues. Through capacity building, studies, and stakeholder consultations, it begins the process of defining and developing health policies appropriate to the country. It also supports a strategy for human resource development, technical assistance, and regulations for pharmaceuticals.'},
   'url': 'https://projects.worldbank.org/en/projects-operations/project-detail/P070294'},
  'P035823': {'id': 'P035823',
   'countryname': ['Islamic Republic of Pakistan'],
   'project_name': 'Protected Areas Management Project',
   'project_abstract': {'cdata': 'The GEF Protected Areas Management Project aims at conserving globally important habitats, and species in three protected areas of Pakistan, within mountain, arid rangeland, estuarine, and marine ecosystems. The components include: 1) Protected area biodiversity management, through the following subcomponents: a) creation of a process framework for participation of custodial communities in park management, and conservation, through Village Conservation Committees; additionally, a technical assistance (TA) entity will provide planning, scientific, and social expertise. Community orientation, and mobilization will be provided, to map the community resource utilization, and develop resource management strategies, and mitigation measures; b) formulation of detailed park management, and strategy, integrated into community micro-planning, and micro-enterprise initiatives in accordance with environmental programs, and traditional ecological knowledge; c) improvement of park infrastructure; d) improvement of park operations; e) development of a baseline resource inventory, habitat improvement research, and wildlife enrichment; and, f) creation of public environmental awareness, and outreach programs. 2) Promotion of public/private cooperation for long-term biodiversity conservation, by providing TA, and supporting cost-sharing arrangements, and, income-generating activities. 3) Support an institutional capacity building training program, with topics ranging from legal, and policy reform, to tourism management, and plans. 4) Project coordination for the development of policy, and legislation relating to protected areas, ensuring standardized systems. Eco-tourism opportunities will be evaluated through the Tourism Development and Marketing Study.'},
   'url': 'https://projects.worldbank.org/en/projects-operations/project-detail/P035823'},
  'P052368': {'id': 'P052368',
   'countryname': ['Republic of South Africa'],
   'project_name': 'Maloti-Drakensberg Transfrontier Conservation and Development Project',
   'project_abstract': {'cdata': 'The Maloti-Drakensberg Transfrontier Conservation and Development Project aims at conserving the global biodiversity of this distinct area, and, will contribute to community development through income generation from nature-based tourism. The components will: 1) finance bilateral collaboration through the establishment of a Steering Committee, National Project Coordination Committees, and coordination offices in South Africa and Lesotho. Joint technical working groups will also be established, to develop and implement action plans, focused on topics such as nature-based tourism, marketing, and management activities, while communication linkages will include a knowledge management system; 2) plan a strategic conservation, based on stakeholder consultation, and conceptual proposals for compatible land-uses. Conservation planning at the landscape level will be designed to facilitate bilateral involvement, and, a participatory bio-diversity monitoring system will ensure cross-boundary conservation, supplementing resources of the nature conservation agencies, to ensure sound planning, and actions; 3) ensure protected area planning for existing, and proposed conservation areas, through planning and zoning development, area management, and business planning; 4) manage conservation of existing protected areas, focusing on the control of alien invading plant species, and supporting through incremental costs, the rehabilitation of management roads, improvement of flora and fauna conservation, prioritizing on endangered species; 5) manage conservation of planned protected areas, following strategies as devised under component 4, prioritizing on the issue of overgrazing, and loss of wetlands; 6) involve community participation, emphasizing on targeted training in conservation, nature-based tourism, craft production, etc.; 7) develop nature-based tourism, emphasizing on community-'},
   'url': 'https://projects.worldbank.org/en/projects-operations/project-detail/P052368'},
  'P037580': {'id': 'P037580',
   'countryname': ['Republic of Benin'],
   'project_name': 'National Parks Conservation and Management Project',
   'project_abstract': {'cdata': "The National Parks Conservation and Management Program Project, will ensure sustainable management, and conservation of regional, and global bio-diversity in Benin, including fragile ecosystems in the northern areas. It will specifically, establish sustainable wildlife management, and bio-diversity conservation capacity, at both national, and local levels. The components are: 1) to provide program management, through planning and monitoring at the national level, of habitats and ecosystems, and, support actions on legal aspects, and regional cooperation, through training, and ecological monitoring; 2) to support natural resources conservation at the Pendjari National Park, through adequate management of the park and cynegetic areas, thus, enabling tourism, and hunting practices, and, includes community participation, at the local level, in the development of the Siri area, and, the Tanguieta - Porga/Batia axes; and, 3) to support conservation of the W National Park, also, through appropriate management of its park and cynegetic areas, and community involvement. While the global environmental objective, will ensure long-term conservation of the country's bio-diversity, operational objectives will ensure increased managerial capacity of partnerships, and local communities, and, institutional capacity building will be supported through the Global Environmental Facility."},
   'url': 'https://projects.worldbank.org/en/projects-operations/project-detail/P037580'},
  'P074819': {'id': 'P074819',
   'countryname': ['Plurinational State of Bolivia'],
   'project_name': 'National Land Administration (Supplemental)',
   'project_abstract': {'cdata': "The objectives of the National Land Administration Project will be to achieve a more efficient and transparent land administration system, clarify the land tenure situation, identify public land suitable for small farmer settlements and promote a more sustainable use of the country's land resources. The project will have a major component improving the land administration system within the current framework and a minor component implementing the legal and institutional land administration reforms, if and when they are introduced. The major component will support the formulation of a sound and coherent land policy and legislation, carry out land mapping on three million ha to obtain cadastre information and to regularize the land tenure situation wherever possible, indentify 500,000 ha suitable for small farmer settlement and increase the efficiency and transparency of the land administration system. In addition, the project will also finance: 1) title regularization and land settlement programs by the National Land Institute, when established; and 2) the introduction of an integrated legal cadastral registry system when the Legal Cadastral Registry is established."},
   'url': 'https://projects.worldbank.org/en/projects-operations/project-detail/P074819'},
  'P057459': {'id': 'P057459',
   'countryname': ['Argentine Republic'],
   'project_name': 'Sustainable Fisheries Management Project',
   'project_abstract': {'cdata': 'The Sustainable Fisheries Management Project, will identify innovative, cost-effective mechanisms for strengthening fisheries management capacity, in accord with the strategic context to modernize the role of the public sector. The components will: 1) strengthen the management capacity of the Secretariat of Agriculture, Livestock, Fisheries and Food (SAGPyA), particularly those functions required under the Quota Management System, including identification of service requirements, and cost effective mechanisms for service delivery. Local, and foreign technical assistance (TA) will be financed to review key functional responsibilities, and propose institutional, and operational modifications, including provision of equipment, and training needs; 2) strengthen monitoring, control and surveillance functions of SAGPyA, through: the development of license, and quota registry; improved fisheries inspection services; and, a pilot on-board observer program to address research needs. Information, and communication systems will be developed, supported by improved hardware/software infrastructure; 3) pilot social assistance action centers for unemployed fisheries workers, assessing existing labor programs, targeting vulnerable industry workers in coordination with cooperatives, unions, and industry as a whole; and, 4) provide administrative support for project implementation.'},
   'url': 'https://projects.worldbank.org/en/projects-operations/project-detail/P057459'},
  'P035917': {'id': 'P035917',
   'countryname': ['Republic of Malawi'],
   'project_name': 'Mulanje Mt. Biodiversity Conservation Project',
   'project_abstract': {'cdata': "The Mulanje Mountain Biodiversity Conservation Project will contribute to increase awareness on the value of biodiversity within the project area, among the Forest Department (FD), and surrounding communities alike, ensuring that conservation needs are addressed, strengthening FD's capacity, and, encouraging greater community participation in forest management. The components include: 1) establishment of the Trust Administration Unit (TAU), within the Mulanje Mountain Conservation Trust (MMCT), to develop the program content for biodiversity conservation, research/monitoring, environmental education, and, forest co-management, in collaboration with the FD, and nongovernmental organizations. The capacity building element will relate to the coordinating functions of MMCT, including training, inter alia, in Trust accounts, reporting requirements, and procurement; 2) activities to support a biodiversity baseline survey, and monitoring; capacity building for biodiversity protection, management, and monitoring; direct operational conservation activities, and equipment; and, research on biodiversity conservation; 3) assessment of local primary/secondary schools' involvement in promoting environmental awareness, and, participatory planning, and design of program activities for the development of environmental education; 4) forest co-management, and sustainable livelihoods, emphasizing linkages between economic benefits, indigenous biodiversity, and natural ecosystems; and, 5) establishment of the Conservation Trust Fund, through the MMCT, to sustain biodiversity conservation within an ecological sustainable context."},
   'url': 'https://projects.worldbank.org/en/projects-operations/project-detail/P035917'},
  'P066065': {'id': 'P066065',
   'countryname': ['Romania'],
   'project_name': 'Agricultural Pollution Control GEF Project',
   'project_abstract': {'cdata': "The Agricultural Pollution Control Project for Romania aims to increase significantly the use of environment-friendly agricultural practices in the project area and thereby reduce nutrient discharge from agricultural sources in Romania to the Danube River and Black Sea. There are three main components. The first has four sub-components: it 1) provides incentives for the installation of improved manure storage facilities and equipment for manure collection and application in the seven comunas; 2) promotes the adoption of better agricultural practices to improve agricultural production while reducing nutrient discharge pollution for agriculture; 3) develops and supports a specific land use management plan for the Boianu-Sticleanu Polder and ecological restoration of the Calderasi-Raul Polder; and 4) strengthens capacity in Calarasi Judet and the public health directorate to monitor soil and water quality and environmental impacts. The second component strengthens national policy and regulatory capacity. The third component finances a broad public information campaign of the project's activities and benefits at the local, national, and regional levels to achieve replicability of project interventions."},
   'url': 'https://projects.worldbank.org/en/projects-operations/project-detail/P066065'}},
 'facets': {}}